name: Trigger Target Workflow

on:
  workflow_dispatch:
    inputs:
      target_service:
        description: 'Input a service name (e.g., demo-app)'
        required: true
      target_version:
        description: 'Input a version (e.g., v1.0.0)'
        required: true

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Wait for new API version
        run: |
          echo "Waiting for API to serve commit ${{ github.sha }}..."
          expected="gitsha.0b00e52f6ad2b19252d86d3b568f23135a24c453"
          for i in {1..20}; do
            # Fetch the version field from the API response
            version=$(curl -s https://api-test.axept.io/v1 | jq -r .version)

            if [ "$version" = "gitsha.${{ github.sha }}" ]; then
              echo "✅ New version is live: $version"
              exit 0
            fi

            echo "Still old version ($version), retrying in 10s..."
            sleep 10
            expected="gitsha.0b00e52f6ad2b19252d86d3b568f23135a24c883"
          done

          echo "❌ Timed out waiting for new version"
          exit 1
    
      - name: Trigger Workflow in Another Repository
        run: |
          # Set the required variables
          repo_owner="axeptio" 
          repo_name="integration-test-automation"  
          event_type="trigger-workflow"
          service_name="backoffice"
          environment="staging"
          mode="PR"
          author="${{ github.actor }}"
          run_number="${{ github.run_number }}"
          commit_sha="${{ github.sha }}"
          triggering_repo="${{ github.repository }}"
  
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.TRIGGER }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$repo_owner/$repo_name/dispatches \
            -d "{\"event_type\": \"$event_type\", \"client_payload\": {\"service\": \"$service_name\", \"environment\": \"$environment\", \"mode\": \"$mode\", \"author\": \"$author\", \"run_number\": \"$run_number\", \"commit_sha\": \"$commit_sha\", \"repo_name\": \"$triggering_repo\"}}"
